version: "2"

linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - goprintffuncname
    - gosec
    - lll
    - misspell
    - mnd
    - nakedret
    - noctx
    - nolintlint
    - revive
    - sloglint
    - staticcheck
    - testifylint
    - unconvert
    - unparam
    - whitespace
  settings:
    gosec:
      excludes:
        - G404
    govet:
      disable:
        - fieldalignment
    sloglint:
      no-mixed-args: false
      attr-only: true
      context: all
      static-msg: true
      no-raw-keys: false
      key-naming-case: snake
      args-on-sep-lines: true

  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - errcheck
          - funlen
          - gocyclo
          - gosec
          - mnd
        path: _test.go
    paths:
      - .go
      - direnv
      - internal/options/store/db
      - third_party$
      - builtin$
      - examples$

formatters:
  enable:
    - gofumpt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - gitlab.com/hmajid2301/optinix
  exclusions:
    generated: lax
    paths:
      - .go
      - direnv
      - internal/options/store/db
      - third_party$
      - builtin$
      - examples$
