version: "3"

tasks:
  build:
    desc: Builds the app into a binary.
    cmds:
      - go build main.go

  lint:
    desc: Runs the linter.
    cmds:
      - golangci-lint run {{.CLI_ARGS}}

  format:
    desc: Runs the formatter.
    cmds:
      - goimports -local gitlab.com/majiy00/go/clis/optinix -w .

  tests:unit:
    desc: Runs all the unit tests.
    cmds:
      - go test -tags=unit -v ./...

  tests:integration:
    desc: Runs all the integration tests tests.
    cmds:
      - go test -tags=integration -v ./...

  coverage:
    desc: Run the integration tests and gets the code coverage
    cmds:
      - go install github.com/boumenot/gocover-cobertura@latest
      - go test -coverprofile=coverage.txt -tags=all -v ./... | tee output.txt
      - cat output.txt | go-junit-report -set-exit-code > report.xml
      #- gocover-cobertura < coverage.txt > coverage.xml

