version: "3"

tasks:
  build:
    desc: Builds the app into a binary.
    cmds:
      - go build main.go

  lint:
    desc: Runs the linter.
    cmds:
      - golangci-lint run {{.CLI_ARGS}}

  docker:
    desc: Create Docker image from Nix
    cmds:
      - nix build .#dockerImage
      - ./result | docker load

  format:
    desc: Runs the formatter.
    cmds:
      - goimports -local gitlab.com/hmajid2301/optinix -w .

  tests:unit:
    desc: Runs all the unit tests.
    cmds:
      - go test -v -short ./...

  tests:integration:
    desc: Runs all the integration tests.
    cmds:
      - go test -run Integration -v ./...

  tests:
    desc: Runs all the tests.
    cmds:
      - go test -run ./...

  coverage:
    desc: Run the integration tests and gets the code coverage
    cmds:
      - go test -covermode count -coverprofile=coverage.txt -v ./... | tee output.txt
      - cat output.txt | go-junit-report -set-exit-code > report.xml
      - gocover-cobertura < coverage.txt > coverage.xml

