// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Option struct {
	ID           int64
	CreatedAt    sql.NullTime
	UpdatedAt    sql.NullTime
	Name         string
	Description  string
	Type         string
	DefaultValue string
	Example      string
}

type Source struct {
	ID        int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
	Url       string
}

type SourceOption struct {
	SourceID  int64
	OptionID  int64
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}
